
name: Flutter Web
on:
  push:
    branches:
      - master
      
permissions:
  contents: read
  pages: write
  id-token: write      

jobs:
  build:
    name: Build Web

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - name: Create .env variables
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BACKEND_URL: ${{ secrets.BACKEND_URL }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
            
      - name: Build Flutter application
        run: |
            flutter config --enable-web
            flutter build web --no-null-assertions --no-native-null-assertions --release --web-renderer html

      - name: Deploy
        run: aws s3 sync ./build/web s3://quicker-webapp
